{
  lib,
  rustPlatform,
  installShellFiles,
  makeWrapper,
  nftables,
  systemd,
}:

rustPlatform.buildRustPackage {
  pname = "regionlock";
  version = "1.0.0";

  src = lib.cleanSourceWith {
    src = ../.;
    # Keep the build input pure: source, lockfile, fixtures, packaging.
    filter =
      path: type:
      let
        rel = lib.removePrefix (toString ../. + "/") (toString path);
      in
      lib.any (p: lib.hasPrefix p rel || p == rel) [
        "Cargo.toml"
        "Cargo.lock"
        "regionlock"
        "regionlock-core"
        "regionlock-apply"
        "packaging"
        "LICENSE"
      ];
  };

  cargoLock.lockFile = ../Cargo.lock;

  nativeBuildInputs = [
    installShellFiles
    makeWrapper
  ];

  # The privileged applier runs under pkexec, which sanitizes PATH. Give it
  # an explicit PATH so it can find nft and systemctl. The user CLI is left
  # unwrapped: escalators (pkexec/sudo) must resolve from the system setuid
  # wrappers, and ping benefits from the system's capability-endowed binary.
  postInstall = ''
    wrapProgram $out/bin/regionlock-apply \
      --prefix PATH : ${
        lib.makeBinPath [
          nftables
          systemd
        ]
      }

    # Completions and man page are generated by the binary itself (hidden
    # `generate` subcommand) so they never drift from the grammar.
    installShellCompletion --cmd regionlock \
      --bash <($out/bin/regionlock generate completions bash) \
      --zsh  <($out/bin/regionlock generate completions zsh) \
      --fish <($out/bin/regionlock generate completions fish)
    $out/bin/regionlock generate completions nu > regionlock.nu
    installShellCompletion --name regionlock.nu regionlock.nu

    $out/bin/regionlock generate man > regionlock.1
    installManPage regionlock.1

    # polkit action for the applier. Rewrite the exec.path from the distro
    # default (/usr/bin) to this build's actual applier path, so pkexec
    # matches OUR action (custom message, auth_admin_keep caching) instead
    # of falling back to the generic org.freedesktop.policykit.exec action.
    install -Dm644 packaging/org.pengeg.regionlock.policy \
      $out/share/polkit-1/actions/org.pengeg.regionlock.policy
    substituteInPlace $out/share/polkit-1/actions/org.pengeg.regionlock.policy \
      --replace-fail /usr/bin/regionlock-apply $out/bin/regionlock-apply

    # Static systemd unit files, for non-NixOS packaging / reference. On
    # NixOS the module defines the units itself (store path -> the applier
    # detects module management and skips systemctl).
    for unit in regionlock.service regionlock-refresh.service regionlock-refresh.timer; do
      install -Dm644 packaging/$unit $out/lib/systemd/system/$unit
    done
  '';

  # Exercised at build time; the privileged e2e stays out of the sandbox.
  doCheck = true;

  meta = {
    description = "Linux CLI server picker for Steam Datagram Relay games";
    homepage = "https://github.com/gegnep/regionlock";
    license = lib.licenses.gpl3Only;
    mainProgram = "regionlock";
    platforms = lib.platforms.linux;
  };
}
