# regionlock build + install Makefile, for non-Nix (FHS) packaging.
#
# Usage:
#   make               # build release binaries
#   sudo make install  # install under PREFIX (default /usr/local)
#
# Distro packages set PREFIX=/usr and stage into DESTDIR:
#   make build
#   make install PREFIX=/usr DESTDIR="$pkgdir"
#
# Note: systemd reads units from /usr/lib and /etc, not /usr/local/lib, so a
# PREFIX=/usr/local install leaves the units where systemd will not find them.
# Set PREFIX=/usr (or override SYSTEMDDIR) for working boot persistence.

PREFIX      ?= /usr/local
DESTDIR     ?=
CARGO       ?= cargo
INSTALL     ?= install

BINDIR      ?= $(PREFIX)/bin
LIBDIR      ?= $(PREFIX)/lib
DATADIR     ?= $(PREFIX)/share
MANDIR      ?= $(DATADIR)/man/man1
SYSTEMDDIR  ?= $(LIBDIR)/systemd/system
POLKITDIR   ?= $(DATADIR)/polkit-1/actions
LICENSEDIR  ?= $(DATADIR)/licenses/regionlock
BASHCOMPDIR ?= $(DATADIR)/bash-completion/completions
ZSHCOMPDIR  ?= $(DATADIR)/zsh/site-functions
FISHCOMPDIR ?= $(DATADIR)/fish/vendor_completions.d
NUCOMPDIR   ?= $(DATADIR)/regionlock

# Host binary used to generate completions and the man page. Native builds
# only; a cross build must point this at a runnable host binary.
GEN         ?= target/release/regionlock

.PHONY: all build test install uninstall clean

all: build

build:
	$(CARGO) build --release --locked

test:
	$(CARGO) test --release --locked --workspace

install:
	@test -x target/release/regionlock && test -x target/release/regionlock-apply || \
		{ echo 'error: binaries not built; run "make build" first' >&2; exit 1; }

	# Binaries. regionlock-apply MUST land at $(BINDIR)/regionlock-apply so
	# the polkit exec.path below matches it.
	$(INSTALL) -Dm755 target/release/regionlock       $(DESTDIR)$(BINDIR)/regionlock
	$(INSTALL) -Dm755 target/release/regionlock-apply $(DESTDIR)$(BINDIR)/regionlock-apply

	# polkit action. Rewrite exec.path to the install prefix so pkexec
	# matches OUR action (custom message + auth_admin_keep caching) instead
	# of the generic org.freedesktop.policykit.exec fallback.
	$(INSTALL) -Dm644 packaging/org.pengeg.regionlock.policy \
		$(DESTDIR)$(POLKITDIR)/org.pengeg.regionlock.policy
	sed -i 's#/usr/bin/regionlock-apply#$(BINDIR)/regionlock-apply#' \
		$(DESTDIR)$(POLKITDIR)/org.pengeg.regionlock.policy

	# systemd units.
	$(INSTALL) -Dm644 packaging/regionlock.service \
		$(DESTDIR)$(SYSTEMDDIR)/regionlock.service
	$(INSTALL) -Dm644 packaging/regionlock-refresh.service \
		$(DESTDIR)$(SYSTEMDDIR)/regionlock-refresh.service
	$(INSTALL) -Dm644 packaging/regionlock-refresh.timer \
		$(DESTDIR)$(SYSTEMDDIR)/regionlock-refresh.timer

	# Shell completions, generated by the binary so they never drift.
	$(INSTALL) -d $(DESTDIR)$(BASHCOMPDIR) $(DESTDIR)$(ZSHCOMPDIR) \
		$(DESTDIR)$(FISHCOMPDIR) $(DESTDIR)$(NUCOMPDIR)
	$(GEN) generate completions bash > $(DESTDIR)$(BASHCOMPDIR)/regionlock
	$(GEN) generate completions zsh  > $(DESTDIR)$(ZSHCOMPDIR)/_regionlock
	$(GEN) generate completions fish > $(DESTDIR)$(FISHCOMPDIR)/regionlock.fish
	$(GEN) generate completions nu   > $(DESTDIR)$(NUCOMPDIR)/regionlock.nu

	# Man page.
	$(INSTALL) -d $(DESTDIR)$(MANDIR)
	$(GEN) generate man > $(DESTDIR)$(MANDIR)/regionlock.1

	# License.
	$(INSTALL) -Dm644 LICENSE $(DESTDIR)$(LICENSEDIR)/LICENSE

uninstall:
	rm -f $(DESTDIR)$(BINDIR)/regionlock
	rm -f $(DESTDIR)$(BINDIR)/regionlock-apply
	rm -f $(DESTDIR)$(POLKITDIR)/org.pengeg.regionlock.policy
	rm -f $(DESTDIR)$(SYSTEMDDIR)/regionlock.service
	rm -f $(DESTDIR)$(SYSTEMDDIR)/regionlock-refresh.service
	rm -f $(DESTDIR)$(SYSTEMDDIR)/regionlock-refresh.timer
	rm -f $(DESTDIR)$(BASHCOMPDIR)/regionlock
	rm -f $(DESTDIR)$(ZSHCOMPDIR)/_regionlock
	rm -f $(DESTDIR)$(FISHCOMPDIR)/regionlock.fish
	rm -f $(DESTDIR)$(NUCOMPDIR)/regionlock.nu
	rm -f $(DESTDIR)$(MANDIR)/regionlock.1
	rm -f $(DESTDIR)$(LICENSEDIR)/LICENSE

clean:
	$(CARGO) clean
